spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

mopl:
  redis:
    watching-session:
      ttl: ${WATCHING_SESSION_TTL:24h}
