spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 300
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mopl?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_SPRING_DATASOURCE_USERNAME:}
    password: ${LOCAL_SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

---
# =============================================================================
# Test Profile - Testcontainers 기반
# =============================================================================
# Testcontainers가 MySQL 컨테이너를 자동으로 시작하고 연결 정보를 주입합니다.
# spring.datasource.* 설정은 Testcontainers의 @ServiceConnection이 자동 설정합니다.
# =============================================================================
spring.config.activate.on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 100
          time_zone: UTC
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        timezone:
          default_storage: NORMALIZE_UTC
  flyway:
    enabled: false
  sql:
    init:
      mode: never
