spring:
  datasource:
    # In-Memory 방식 (애플리케이션 종료 시 데이터 삭제)
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    # File 방식 (데이터 유지 원할 시 사용) - 경로: ~/testdb.mv.db
    # url: jdbc:h2:file:~/testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC

---
spring.config.activate.on-profile: prod

spring:
  # datasource: MySQL로 변경
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
