spring:
  datasource:
    # In-Memory 방식 (애플리케이션 종료 시 데이터 삭제)
    # url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    # File 방식 (데이터 유지 원할 시 사용) - 경로: ~/testdb.mv.db
    # url: jdbc:h2:file:~/testdb;MODE=MySQL
    url: jdbc:h2:file:~/testdb;MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mopl?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
---
# 추후 삭제 예정입니다.
mopl:
  watching-session:
    repository:
      type: redis  # stub | redis
