spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

---
# =============================================================================
# Test Profile
# =============================================================================
# 테스트에서는 실제 메일을 전송하지 않습니다.
# JavaMailSender를 모킹하거나 GreenMail 등의 테스트 서버를 사용합니다.
# =============================================================================
spring.config.activate.on-profile: test

spring:
  mail:
    host: localhost
    port: 3025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
