mopl:
  search:
    enabled: ${SEARCH_ENABLED:false}
    index:
      recreate-on-startup: ${SEARCH_INDEX_RECREATE_ON_STARTUP:false}
    elasticsearch:
      uris: ${SEARCH_ELASTICSEARCH_URIS:localhost:9200}
      username: ${SEARCH_ELASTICSEARCH_USERNAME:}
      password: ${SEARCH_ELASTICSEARCH_PASSWORD:}
      connect-timeout-millis: ${SEARCH_ELASTICSEARCH_CONNECT_TIMEOUT:1000}
      socket-timeout-millis: ${SEARCH_ELASTICSEARCH_SOCKET_TIMEOUT:3000}
