mopl:
  search:
    enabled: ${ELASTICSEARCH_ENABLED:true}
    elasticsearch:
      uris: ${ELASTICSEARCH_URIS:localhost:9200}
      username: ${ELASTICSEARCH_USERNAME:}
      password: ${ELASTICSEARCH_PASSWORD:}
      connect-timeout-millis: ${ELASTICSEARCH_CONNECT_TIMEOUT:1000}
      socket-timeout-millis: ${ELASTICSEARCH_SOCKET_TIMEOUT:3000}

spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
