mopl:
  search:
    enabled: true
    elasticsearch:
      uris: localhost:9200
      connect-timeout-millis: 1000
      socket-timeout-millis: 3000

spring:
  elasticsearch:
    uris: http://localhost:9200
