mopl:
  storage:
    type: ${STORAGE_TYPE:local}   # local | s3
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.mopl/storage}
      base-url: ${STORAGE_LOCAL_BASE_URL:http://localhost:8080}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY:}
      secret-key: ${AWS_S3_SECRET_KEY:}
      region: ${AWS_S3_REGION:ap-northeast-2}
      bucket: ${AWS_S3_BUCKET:}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:11m}
      endpoint: ${AWS_S3_ENDPOINT:}
